version: "3.9"

services:
  chroma:
    image: chromadb/chroma:latest
    ports: ["8001:8000"]
    volumes:
      - chroma_data:/chroma/.chroma

  ingestion:
    build:
      context: .                     # project root
      dockerfile: ingestion_service/Dockerfile
    env_file: .env
    ports: ["8003:8000"]
    volumes:
      - ./ingestion_service:/code
      - ./chroma_data:/data/chroma

volumes:
  chroma_data:
