version: "3.9"

services:
  chroma:
    image: chromadb/chroma:0.6.3
    ports: ["8001:8000"]
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
    volumes:
      - chroma_data:/chroma/chroma
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  ingestion:
    build:
      context: .
      dockerfile: ingestion_service/Dockerfile
    env_file: .env
    ports: ["8003:8000"]
    volumes:
      - ./ingestion_service:/code
    depends_on:
      chroma:
        condition: service_healthy

  qa:
    build:
      context: .
      dockerfile: qa_service/Dockerfile
    env_file: .env
    depends_on:
      chroma:
        condition: service_healthy
    ports: ["8004:8000"]

  streamlit:
    build:
      context: .
      dockerfile: streamlit_service/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - INGEST_URL=http://ingestion:8000/api/v1/ingest
      - ASK_URL=http://qa:8000/api/v1/ask
      - ARTIST_URL=http://ingestion:8000/api/v1/artist
    depends_on:
      - ingestion
      - qa

volumes:
  chroma_data:
